### ISSUE TITLE
Javascript object equivalence failure

### ISSUE THREAD

**Issue by am17torres** [knegusen/redux-test-utils#1]
I'm running a test using the `createMockStore` and I found a problem with checking if an action with a payload has been dispatched. 

Repro steps:

__src/actions/index.tsx__
```typescript
export const { incrementEnthusiasm, decrementEnthusiasm } = createActions({
    INCREMENT_ENTHUSIASM: () => ({amount: 1}),
    DECREMENT_ENTHUSIASM: () => ({amount: -1})
})
```
__src/containers/Hello.tsx__
```typescript
export function mapDispatchToProps(dispatch: Dispatch<actions.EnthusiasmAction>) {
  return {
    onIncrement: () => dispatch(actions.incrementEnthusiasm()),
    onDecrement: () => dispatch(actions.decrementEnthusiasm()),
  }
}
```

__src/containers/Hello.test.tsx__
```typescript
expect(store.isActionDispatched(decrementEnthusiasm())).toBeTruthy()
```

*debugging:*
```typescript
console.log(store.getActions(decrementEnthusiasm().type))
// [ { type: 'DECREMENT_ENTHUSIASM', payload: { amount: -1 } } ]
console.log(decrementEnthusiasm())
// { type: 'DECREMENT_ENTHUSIASM', payload: { amount: -1 } }
```

The problem is you are checking if the two objects are equal (references to the same object) instead of checking whether or not the keys and values are equal. Since I'm creating an implicit object every time, they will never be equal.

https://github.com/knegusen/redux-test-utils/blob/c55bf0ffaabcd6349ea5ffa09ba7b8cca9ccf973/src/utils/DispatchMock.js#L35

There are a [number](https://stackoverflow.com/a/1144249/238638) [of](https://github.com/ReactiveSets/toubkal/blob/master/lib/util/value_equals.js) [ways](https://lodash.com/docs/4.17.4#isEqual) to check for object equivalence. I was just going to use lodash because I didn't feel like resolving this problem but I don't know how you feel about adding that dependency to your project so I'll leave it to you.

**Comment by knegusen** [comment]
Hm. I usually use ` getAction('type') ` and then check all fields, but you are right, maybe we could change the way `isActionDispatched` is comparing the objects. I will try to get some time to look at this.
